#!/usr/bin/env python3

"""Program to generate HTML documentation for a Swift package."""


import json
import logging
import os
import shutil
import subprocess

from typing import Dict, List


def _run(command: str, directory: str = None):
    logging.debug("Running command: %s", command)
    subprocess.run(f"{command}", shell=True, check=True, cwd=directory)

def _get_run(command: str, directory: str = None) -> str:
    logging.debug("Running command: %s", command)
    res = subprocess.run(f"{command}", shell=True, check=True, cwd=directory,
                         stdout=subprocess.PIPE)
    return res.stdout.decode('utf-8').strip()

def _get_products_from(package: Dict) -> List:
    products = []
    for product in package.get('products', []):
        products.append(product['name'])
    logging.debug("Found products: %s", products)
    return products

def _recreate_docs_directory():
    if os.path.isdir('docs'):
        shutil.rmtree('docs')
    os.mkdir('docs')

def _generate_docs_for(target: str, version: str, create_subdirs: bool):
    logging.info("Generating docs for %s", target)
    command = "jazzy"
    command += f" --module={target}"
    command += f" --module-version='{version}'"
    if create_subdirs:
        command += f" --output='docs/{target}'"
    command += " --use-safe-filenames"
    command += f" --documentation='Sources/{target}/*.md'"
    if os.path.isfile('logo.png'):
        command += " --docset-icon=logo.png"
    author = os.environ.get('AUTHOR', None)
    if author:
        command += f" --author='{author}'"
    author_url = os.environ.get('AUTHOR_URL', None)
    if os.environ.get('AUTHOR_URL'):
        command += f" --author_url='{author_url}'"
    git_url = _get_run("git config --get remote.origin.url")
    if git_url:
        command += f" --github_url='{git_url}'"
    _run(command)

def _write_index(targets: List, version: str):
    # pylint: disable=line-too-long
    # Justification: Will read more nicely than trying to conform to the limit.
    logging.info("Writing index file")
    package_name = os.path.basename(os.getcwd())
    with open('docs/index.html', 'w', encoding='utf-8') as outfile:
        outfile.write("<!DOCTYPE html>\n")
        outfile.write("<!-- Auto-generated by kss.license.html_report. Do not edit manually. -->\n")
        outfile.write("<html>\n")
        outfile.write("<head>\n")
        outfile.write(f"  <link rel='stylesheet' type='text/css' href='{targets[0]}/css/jazzy.css'/>\n")
        outfile.write(f"  <link rel='stylesheet' type='text/css' href='{targets[0]}/css/highlight.css'/>\n")
        outfile.write("  <meta charset='utf-8'>\n")
        outfile.write("</head>\n")
        outfile.write("<body>\n")
        outfile.write("<article class='main-conent'>\n")
        outfile.write("<section class='section'>\n")
        outfile.write(f"<h1 class='heading'>Index of {package_name}</h1>\n")
        outfile.write(f"<h2>Version {version}</h2>\n")
        outfile.write("<h2>Modules</h2>\n")
        outfile.write("<ul>\n")
        for target in targets:
            outfile.write(f"<li><a href='{target}/index.html'>{target}</a></li>\n")
        outfile.write("</ul>\n")
        outfile.write("</section>\n")
        outfile.write("</article>\n")
        outfile.write("</body>\n")
        outfile.write("</html>\n")


def _main():
    logging.basicConfig(level=logging.DEBUG)
    package = json.loads(_get_run('swift package dump-package'))
    products = _get_products_from(package)
    is_more_than_one_product = len(products) > 1
    version = _get_run("BuildSystem/common/revision.sh")
    _recreate_docs_directory()
    for product in products:
        _generate_docs_for(product, version, is_more_than_one_product)
    if is_more_than_one_product:
        _write_index(products, version)

if __name__ == '__main__':
    if not os.path.isfile('Package.swift'):
        raise RuntimeError("This does not appear to be a Swift package")
    _main()
